/* 
Table Schemas & Trigger Setup
*/

CREATE TABLE public.grade_distributions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  term TEXT NOT NULL,
  course_subject TEXT NOT NULL,
  course_name TEXT NOT NULL,
  prof_name TEXT NOT NULL,
  course_number TEXT NOT NULL,
  course_section TEXT NOT NULL,
  total_enrollment SMALLINT NOT NULL,
  a_plus SMALLINT NOT NULL,
  a SMALLINT NOT NULL,
  a_minus SMALLINT NOT NULL,
  b_plus SMALLINT NOT NULL,
  b SMALLINT NOT NULL,
  b_minus SMALLINT NOT NULL,
  c_plus SMALLINT NOT NULL,
  c SMALLINT NOT NULL,
  c_minus SMALLINT NOT NULL,
  d_plus SMALLINT NOT NULL,
  d SMALLINT NOT NULL,
  f SMALLINT NOT NULL,
  w SMALLINT NOT NULL,
  inc SMALLINT NOT NULL,
  avg_gpa REAL NULL,
  CONSTRAINT grade_distributions_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  prof_name TEXT NOT NULL,
  course_subject TEXT NOT NULL,
  course_number TEXT NOT NULL,
  rating SMALLINT NOT NULL,
  title TEXT NOT NULL,
  comment TEXT NOT NULL,
  term TEXT NOT NULL,
  user_id UUID NOT NULL DEFAULT auth.uid(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  -- Limit the student user to writing one review per professor-course combination
  CONSTRAINT one_review_per_course UNIQUE (user_id, prof_name, course_subject, course_number),
  -- Deletes user's reviews upon user account deletion. Could be altered later to ON DELETE SET NULL to grant
  -- users the option to leave their reviews as anonymous upon account deletion but user_id would have to be altered to be nullable.
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  -- Prevent empty strings or whitespace-only submissions
  CONSTRAINT check_prof_not_empty CHECK (TRIM(BOTH FROM prof_name) <> ''),
  CONSTRAINT check_subject_not_empty CHECK (TRIM(BOTH FROM course_subject) <> ''),
  CONSTRAINT check_title_not_empty CHECK (TRIM(BOTH FROM title) <> ''),
  CONSTRAINT check_comment_not_empty CHECK (TRIM(BOTH FROM comment) <> ''),
  CONSTRAINT check_course_number_not_empty CHECK (TRIM(BOTH FROM course_number) <> ''),
  -- Match the database limits to the frontend character limits
  CONSTRAINT check_comment_length CHECK (LENGTH(comment) <= 1000),
  CONSTRAINT check_title_length CHECK (LENGTH(title) <= 80),
  -- Validate rating bounds
  CONSTRAINT check_rating_range CHECK (rating >= 1 AND rating <= 5),
  -- Enforce academic term format (e.g., "Fall 2025")
  CONSTRAINT check_valid_term CHECK (term ~ '^(Fall|Spring|Summer|Winter) 20[0-9]{2}$')
) TABLESPACE pg_default;

-- Create the composite index to optimize the trigger lookup in grade_distributions
CREATE INDEX IF NOT EXISTS idx_grade_distributions_prof_course 
ON public.grade_distributions USING btree (prof_name, course_subject, course_number) TABLESPACE pg_default;

-- Ensures reviews can only be submitted for valid prof/course combos
CREATE OR REPLACE FUNCTION check_valid_course()
RETURNS TRIGGER AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.grade_distributions
    WHERE prof_name = NEW.prof_name
      AND course_subject = NEW.course_subject
      AND course_number = NEW.course_number
  ) THEN
    RAISE EXCEPTION 'This professor and course combination does not exist in the grade records.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS enforce_valid_course ON public.reviews;
CREATE TRIGGER enforce_valid_course
BEFORE INSERT OR UPDATE ON public.reviews
FOR EACH ROW EXECUTE FUNCTION check_valid_course();